# Generated by Django 4.2.3 on 2023-07-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iden', '0002_prediction_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trainings/')),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
